services:
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: article_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: article_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./php-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: